### ISSUE TITLE
Bass support pls add

### ISSUE THREAD

**Issue by Trapezanidou** [robertkirkman/sm64ex-coop#2]
Pls add bass support on the android version PLSSSS

**Comment by robertkirkman** [comment]
I will not add any proprietary binaries to the repository, but I am working on a solution to play the sounds without having BASS

**Comment by Trapezanidou** [comment]
On beta 35?

Στις Κυρ, 11 Ιουν 2023, 21:30 ο χρήστης Robert Kirkman <
***@***.***> έγραψε:

**Comment by robertkirkman** [comment]
It will be an update to my version that comes independently from the djoslin0 version's feature updates, unless someone else creates an acceptable solution before I do.

**Comment by LucasMerinoC** [comment]
Hopefully an update will be released, but ask, will it be a separate repository in Termux or will it come in the update in git?

**Comment by robertkirkman** [comment]
> Hopefully an update will be released, but ask, will it be a separate repository in Termux or will it come in the update in git?

you can expect any sound code I add to be either in this repository or in added git submodules within this repository the same way coopnet is packaged here.

**Comment by robertkirkman** [comment]
An example of playing the mod sounds without having BASS has been created by Isaac0-dev and posted [here](https://github.com/coop-deluxe/sm64coopdx/commit/4473bfffe932a30e5356c5c50243224b9914d61b). That change looks satisfactory to me at first glance and might eventually come to this repository, but not quickly because I will probably be making a large number of other changes simultaneously.

**Comment by robertkirkman** [comment]
Fixed in e11e3a340f744ce443fc05437c7d8a405434ac3e
