### ISSUE TITLE
how do i use the star icon?

### ISSUE THREAD

**Issue by Aust20156** [robertkirkman/sm64ex-coop#25]
i can use it here like this: ★ but in-game it doesn't work. and i tried every letter, number, and symbol. help?

**Comment by robertkirkman** [comment]
in-game chat in sm64ex-coop only supports a specific set of characters in order to limit possible user input codepaths to a reasonable number, and [Unicode Character “★” (U+2605)](https://www.compart.com/en/unicode/U+2605) is not among the supported characters. This behavior matches the Desktop version of the game.

**Comment by robertkirkman** [comment]
If you're talking about a star like this,

![image](https://github.com/user-attachments/assets/0d4c4865-f3f3-4d49-841e-3a7bbc02cb36)

[That](https://github.com/robertkirkman/sm64ex-coop/blob/e11e3a340f744ce443fc05437c7d8a405434ac3e/bin/custom_font.c#L24)'s not a normal Unicode ★, it's actually a [0x7F](https://www.compart.com/en/unicode/U+007F), the ASCII/Unicode `DEL` character. I don't know why they picked it to be like that, but it's probably just because they [placed its texture immediately to the right of the `~` symbol in the font bitmap](https://github.com/robertkirkman/sm64ex-coop/blob/e11e3a340f744ce443fc05437c7d8a405434ac3e/textures/custom_font/custom_font_normal.rgba32.png). 

You can already use that symbol in your name on Android or any other version of the game by copying and pasting the [0x7F that's placed here for you on the codepoints.net website](https://codepoints.net/U+007F) into the `coop_player_name` field of the `/storage/emulated/0/com.owokitty.sm64excoop/user/sm64config.txt` file using the [ACode app](https://f-droid.org/en/packages/com.foxdebug.acode/). Use the [Hacker's Keyboard app](https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/) to get reliable copy and paste on Android by using its Ctrl + C and Ctrl + V button combinations. Here's a tutorial video. 


[star.webm](https://github.com/user-attachments/assets/1ad48595-9f72-4e45-b29a-d298d0764541)

**Comment by robertkirkman** [comment]
In version 36.1 the star character looks more or less identical to U+2605, but in version 37+ it has little eyes. To get that change you can wait for #19 .
