### ISSUE TITLE
SDL Error upon launching the game

### ISSUE THREAD

**Issue by frog8412** [robertkirkman/sm64ex-coop#30]
**Describe the bug**
Opening the game results in an SDL Error.

**To Reproduce**
1. bash <(curl -s https://raw.githubusercontent.com/robertkirkman/termux-packages/master/packages/bash/bin-build-sm64ex-coop.sh)
2. Install .apk file
3. Open the game

**Expected behavior**
The game would launch as usual.

**Screenshots**
![Screenshot_2024-08-18-14-19-54-380_com owokitty sm64excoop](https://github.com/user-attachments/assets/40b90ae5-9cb4-4301-a5a2-8bb5eef8eee0)

**Smartphone (please complete the following information):**
 - Device: Xiaomi POCO M5s
 - OS: Android 13; 2207117BPG Build/TP1A.220624.014
 - Browser Google Chrome
 - Version 127.0.6533.103

**Comment by robertkirkman** [comment]
Hi that is caused by **accidentally having Termux's `libglvnd` graphics driver package installed before you run the builder**. Refer to step 16 of the [manual build steps documentation](https://github.com/robertkirkman/sm64ex-coop/blob/android/README_android.md).

If you need to keep the `libglvnd` graphics driver for something else, **please refer to the [X11 mode build directions](https://github.com/robertkirkman/sm64ex-coop?tab=readme-ov-file#how-to-get-this-mode)**.

I understand the root cause of the problem and might create a better solution in the future, but at the present time,
**This is one of the primary reasons why I encourage users encountering this type of error to _use the [sm64ex-coop builder Termux](https://github.com/robertkirkman/termux-app/releases/download/v0.1.2/termux-app_v0.1.2+apt-android-7-github-debug_universal.apk), not their own Termux_**

[sm64ex-coop builder Termux](https://github.com/robertkirkman/termux-app/releases/download/v0.1.2/termux-app_v0.1.2+apt-android-7-github-debug_universal.apk) **prevents this error.**

**Comment by frog8412** [comment]
oh right, thanks
